version: '3.8'

services:
  postgres:
    container_name: ccca-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=app
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres

